### ISSUE TITLE
PaginatedGui#getPagesNum returns Integer.MAX_VALUE when optional field is not set

### ISSUE THREAD

**Issue by IllusionTheDev** [TriumphTeam/triumph-gui#100]
Hey there, no clue if this is a design flaw.

There's an optional field named `pageSize` in the PaginatedGui class, with an optional setter.
When the value is unset (0), and getPagesNum is called, there is a division by 0, which gets casted to an int returning MAX_VALUE.

Code in question: ![image](https://github.com/TriumphTeam/triumph-gui/assets/28360622/7c993c0f-8b40-4309-bffe-350ad2d9850c)

**Comment by kazuryyx** [comment]
I noticed this too, players could infinitely click on the next button even if there was no page at the next index.
