### ISSUE TITLE
GuiType.HOPPER Click Events Not Firing

### ISSUE THREAD

**Issue by Zilleyy** [TriumphTeam/triumph-gui#11]
When using GuiType#HOPPER for a GUI's type, click events do not get fired. Not even default event.

**Comment by ipsk** [comment]
Apologies for the delay on this issue, I tried a few things then I found out that Spigot doesn't call the event for Hoppers because the InventoryHolder is null. Because of that I decided to remove the Hopper option for now. I'll try finding a work around for this and re-add it.
