### ISSUE TITLE
PaginatedGui not working with bordered filler.

### ISSUE THREAD

**Issue by EncryptSL** [TriumphTeam/triumph-gui#118]
Issue is in version 3.1.8 and 3.1.9.

I think commit in class PaginatedGui#populatePage(), just broke addItem function with combination fillers.

Issue is when you have bordered filler and addItem exactly.

When i revert change i don't have issue.

https://github.com/TriumphTeam/triumph-gui/commit/b2ecc7be994847a3b5207f248f3b77e3db5935f5#diff-837928e75244d714de7a55f57504f6ccd853ffcf916fe4ca3631dccb6bd860fcL408-L412

**Comment by LichtHund** [comment]
Thank you for the find! Fixed on 3.1.10. Should take just a few minutes to fully publish.
