### ISSUE TITLE
ClickEvents not working on GuiType.HOPPER

### ISSUE THREAD

**Issue by MikeNipkow** [TriumphTeam/triumph-gui#123]
For migration to 1.20.6/1.21 I noticed that the click events do not get triggered, if the GuiType is set to HOPPER. Therefore users can just drag the items out of the GUI.
Simply changing the GuiType to CHEST solved the issue for me, maybe the HOPPER is broken since 1.20.6?

Here is the change that solved my issue:
https://github.com/Banarnia-Services/FancyHomes/commit/ddc0f363301727de593293d58f01ac7a94af37ca

**Comment by CantBeKarma** [comment]
I was just about to make an issue about this, glad I'm not the only one who realized lol. Went crazy looking for the issue in my code.

**Comment by LichtHund** [comment]
Yeah this has been an issue for a while, it only happens on Spigot. It requires quite a big rework to make it work again on Spigot. It works perfectly fine on Paper.
