### ISSUE TITLE
Add gui manager

### ISSUE THREAD

**Issue by aDL1n** [TriumphTeam/triumph-gui#129]
I suggest adding a gui manager to manage all open gui's. Add the ability to close all open gui or for a specific player without having a gui instance.

**Comment by LichtHund** [comment]
I'll likely not add this. It is recommended to have a new GUI instance per player and having the close action makes it pretty easy to know when the GUI has been closed. And you don't need the GUI instance to close it for a player, you just need to call `player.closeInventory()`. (remembering to add a tick delay to prevent items from being taken from the inventory.)
