### ISSUE TITLE
ItemBuilder.skull().texture not working

### ISSUE THREAD

**Issue by ImYenil** [TriumphTeam/triumph-gui#132]
I'm using version 1.21.4 of Paper and that code doesn't work

Code
    public ItemStack getItemStack(String token, String path) {
        if (!languagesMap.containsKey(token)) {
            MailMe.debug(Locale.class, "LanguagesMap does not contain  " + token);
            return null;
        }
        ConfigurationSection section = languagesMap.get(token).getConfigurationSection(path);
        if (section == null) {
            MailMe.debug(Locale.class, "Section is null for path: " + path + " and token: " + token);
            return new ItemStack(XMaterial.valueOf(MailMe.getInstance().getConfig().getString("invalid-config-section.material")).parseMaterial());
        }
        XMaterial xMaterial = XMaterial.matchXMaterial(section.getString("material")).orElse(XMaterial.valueOf(MailMe.getInstance().getConfig().getString("invalid-config-section.material")));
        Material material = xMaterial.parseMaterial();

        if (material.equals(Material.AIR)) return new ItemStack(Material.AIR);
        ItemBuilder builder = ItemBuilder.from(material)
                .setName(Utils.colour(section.getString("title")))
                .setLore(Utils.colourList(section.getStringList("lore")).toArray(new String[]{}))
                .setAmount(section.getInt("amount"))
                .glow(section.getBoolean("glow"))
                .addItemFlags(ItemFlag.HIDE_UNBREAKABLE, ItemFlag.HIDE_ATTRIBUTES);

        if (material.equals(XMaterial.PLAYER_HEAD.parseMaterial())) {
            ItemBuilder.skull().texture(section.getString("skull-texture"));
        }

        ItemStack stack = builder.build();
        int modelData = section.getInt("custom-model-data");
        if (modelData != 0) {
            ItemMeta meta = stack.getItemMeta();
            meta.setCustomModelData(section.getInt("custom-model-data"));

            stack.setItemMeta(meta);
        }
        return stack;
    }

yml
  send-to-mailbox:
    title: '&e&lMailbox'
    material: PLAYER_HEAD
    amount: 1
    custom-model-data: 0
    lore: []
    glow: true
    skull-texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjI4NDM1ZDc5MWEwMThmY2E3OTI2ODU0Zjc3ZWNkN2RmMmQxZGYwYjFjMWM3ZjlhNjM4YjhhOTMxZGI5NWEifX19

![2024-12-17_18 55 29](https://github.com/user-attachments/assets/548e3636-3b84-42d3-aed0-8faba2391c04)

**Comment by harry0198** [comment]
This code looks familiar…

**Comment by ImYenil** [comment]
> This code looks familiar…

Yes. I started updating this plugin again

**Comment by xMrAfonso** [comment]
This closed because it was never an issue or...?

**Comment by ImYenil** [comment]
> This closed because it was never an issue or...?

i solved

**Comment by xMrAfonso** [comment]
> i solved

care to share what the issue was?
