### ISSUE TITLE
Listener Re-registration and GUI Title Formatting Support

### ISSUE THREAD

**Issue by extremall-dev** [TriumphTeam/triumph-gui#133]
**Issue Description**  
Hello,  

In my plugin, I use the following method during reload: `HandlerList.unregisterAll(this);`, and then I register the listeners again. However, your listener is not re-registered after this process.  

**Suggestion**  
I recommend implementing a way to create an instance of your library that I can manage directly in my plugin's `onEnable` and `onDisable` methods. This would allow me to properly start the library during `onEnable` and shut it down during `onDisable`.  

Additionally, I need support for `String` titles in GUIs because the `Component` class does not fully support my existing color formatting needs.  

Thank you for considering these improvements!

**Comment by xMrAfonso** [comment]
There is a reason String support is totally unsupported in V4... they should NOT BE USED. Components are the way to go, and changing that because it does not fit your needs, is not really logical. You are free to fork the library though!

Also, how else are you using the library? I assume you want the library to work perfectly on enable and disable because you want to support hot reloading the plugin with /reload or plugmanx (which again, shouldn't be done in the first place).

**Comment by LichtHund** [comment]
@xMrAfonso I don't see anywhere they mentioning using v4. Assume it's not unless specified.

**Comment by LichtHund** [comment]
> In my plugin, I use the following method during reload

What reload? Your own reload command or are you talking about the `/reload` from the server? Either way that does not sound great.

> I need support for String titles in GUIs because the Component class does not fully support my existing color formatting needs.

How so? What kind of formatting do you have that a component can't support? But I'll just say straight a way that no I'll not support string, components have been the way Minecraft handles text for years there is no reason to go back.

**Comment by xMrAfonso** [comment]
> @xMrAfonso I don't see anywhere they mentioning using v4. Assume it's not unless specified.

What I meant to imply with that sentence is that if not even more up-to-date versions don't support it, there should be a valid reason why.

**Comment by extremall-dev** [comment]
Yes my own reload command. [This](https://prnt.sc/nh0_XpPMfpzf) is how I fixed it. But I would like to register your events when using **TriumphGui.init(this);**

About colors, for example I can't use all [these](https://prnt.sc/JKVi_x4VrYET).

**Comment by xMrAfonso** [comment]
> Yes my own reload command. [This](https://prnt.sc/nh0_XpPMfpzf) is how I fixed it. But I would like to register your events when using **TriumphGui.init(this);**
What version of TriumphGuis are you using!?

> About colors, for example I can't use all [these](https://prnt.sc/JKVi_x4VrYET).
Those are legacy colors, they have been unsupported for a while. Components, more specifically [MiniMessage](https://docs.advntr.dev/minimessage/) is used.

**Comment by extremall-dev** [comment]
v3.1.11
Yes I know are legacy colors but my customers still want to use them. Also, legacy versions does not accept Component so needed to use String for title, so I do not know why you not support both options.

**Comment by xMrAfonso** [comment]
> v3.1.11 Yes I know are legacy colors but my customers still want to use them. Also, legacy versions does not accept Component so needed to use String for title, so I do not know why you not support both options.

Just because you and/or your customers want support for it, does not mean it will or should be supported. As Matt already said, it's not going to happen. Legacy colors are outdated and only components are supported. Why support both when only one should be used?

As said, you can always fork the project and add support for it, but it won't happen from matt's side.

**Comment by extremall-dev** [comment]
But you are creating Inventory via [String](https://prnt.sc/384bZ-13a4us) title and not via Component title. So you are converting Component to String. You can support only String and if others want to use Component can do it by converting Component to String. For me this is not a problem I just want to help you guys to improve this library because looks so good.

**Comment by xMrAfonso** [comment]
> But you are creating Inventory via [String](https://prnt.sc/384bZ-13a4us) title and not via Component title. So you are converting Component to String. You can support only String and if others want to use Component can do it by converting Component to String. For me this is not a problem I just want to help you guys to improve this library because looks so good.

Lol. Just, lol. The library won't be improved by adding non sense to it like legacy colors. I think Matt knows the value of his library and what it is worth.

**Comment by extremall-dev** [comment]
I don't asked to support legacy colors, I just asked to support String on title since you are using String to create Inventory in order to keep compatibility with older versions. If using String we can use our prefer method for colors, can still use Component if we convert it to String. Also, on **#updateTitle()** method you support String and that is good.

**Comment by xMrAfonso** [comment]
> I don't asked to support legacy colors, I just asked to support String on title since you are using String to create Inventory in order to keep compatibility with older versions. If using String we can use our prefer method for colors, can still use Component if we convert it to String. Also, on **#updateTitle()** method you support String and that is good.

that is not how it works, it's not simply changing it to string lol

**Comment by extremall-dev** [comment]
Yes I know is adding MiniMessage colors but we can do this and by ourself. But why on create menu is using Component title and when updating menu title is using String (No MiniMesaage support by default here, we need to add our own colors into title String)?

**Comment by xMrAfonso** [comment]
> Yes I know is adding MiniMessage colors but we can do this and by ourself. But why on create menu is using Component title and when updating menu title is using String (No MiniMessage support by default here, we need to add our own colors into title String)?

because of some limitation because the library supports spigot. V4 for ex. is paper only for this exact reason, besides it being better ofc.

**Comment by extremall-dev** [comment]
There is no limitation for this, both methods can support Spigot versions since is not using Component to create inventory. Is using String to create inventory on both cases, in one case (update inventory title) is requesting direct the String title of inventory and on other case (create inventory title) is requesting Component and is converting that Component into String to create inventory. I will wait for the developer of this library.

**Comment by xMrAfonso** [comment]
> There is no limitation for this, both methods can support Spigot versions since is not using Component to create inventory. Is using String to create inventory on both cases, in one case (update inventory title) is requesting direct the String title of inventory and on other case (create inventory title) is requesting Component and is converting that Component into String to create inventory. I will wait for the developer of this library.

Anyways, it won't be supported as already stated.

**Comment by extremall-dev** [comment]
Is already supported, but only on update title inventory method.

**Comment by extremall-dev** [comment]
Actually, I can use a Component to create menu and then I can instant update it via String title and I will fully have what I need.

**Comment by xMrAfonso** [comment]
I am not sure why you keep insisting when it was already said it won't happen. By choice.

**Comment by extremall-dev** [comment]
Yeah, I fully understand this for V4 since is only for Paper version must use Component to create menus.

**Comment by LichtHund** [comment]
Jesus people don't argue here, @xMrAfonso very unnecessary, wait for me to reply.

Anyways @extremall-dev if you _really_ want legacy use the constructor directly even if they are deprecated `new Gui(title)`, you lose on the niceness of the builder but that's going to be the only way.
As for the listeners, what you're doing is honestly fine.
