### ISSUE TITLE
Reopen #24 (method to clear page items)

### ISSUE THREAD

**Issue by thisisfel1x** [TriumphTeam/triumph-gui#26]
Please merge #24, currently I have to use reflections in order to clear existing page items:

`Field list = PaginatedGui.class.getDeclaredField("pageItems"); `
`list.setAccessible(true);`
`ArrayList<GuiItem> actualList = (ArrayList<GuiItem>) list.get(lobbySwitcherGui);`
`actualList.clear();`
`list.set(lobbySwitcherGui, actualList);`

Would be a nice feature

**Comment by bobby29831** [comment]
This can be closed as the a new pull request which fixes this has been merged.

**Comment by thisisfel1x** [comment]
Thanks!
