### ISSUE TITLE
BROKEN INVENTORIES

### ISSUE THREAD

**Issue by Kr1S-D** [TriumphTeam/triumph-gui#36]
Inventories break if you use a gui pages 1.8.x to 1.11.x 1.12.2 seem to work

**Comment by ipsk** [comment]
Please give me more details, what exactly breaks?

**Comment by Kr1S-D** [comment]
https://files.fm/f/yxre2twa9

**Comment by ipsk** [comment]
That still doesn't tell me anything. Please provide code. It works perfectly fine for me in all versions.
Feel free to pass by my discord server as it'd be easier to find your issue.

**Comment by Kr1S-D** [comment]
discord link?

**Comment by BlitzOffline** [comment]
https://discord.com/invite/mmZ6eQ6

it is also on the wiki at the top.

**Comment by iGabyTM** [comment]
@Kr1S-D can we have an update on this?
