### ISSUE TITLE
add function to see the page of the paginated gui (ex. x page of x pages)

### ISSUE THREAD

**Issue by ImFound** [TriumphTeam/triumph-gui#38]
Hi, I ask if you could add a method like:
PaginatedGui#getCurrentPageInt()
PaginatedGui#getPagesInt()

**Comment by iGabyTM** [comment]
https://github.com/TriumphTeam/triumph-gui/blob/5723a261e14657e17165a262f28d5f70d7d8e84b/core/src/main/java/dev/triumphteam/gui/guis/PaginatedGui.java#L287-L289
https://github.com/TriumphTeam/triumph-gui/blob/5723a261e14657e17165a262f28d5f70d7d8e84b/core/src/main/java/dev/triumphteam/gui/guis/PaginatedGui.java#L373-L375
