### ISSUE TITLE
Make Adventure Optional!

### ISSUE THREAD

**Issue by evernife** [TriumphTeam/triumph-gui#39]
Well, Adventure is ""relatively"" new.

I don't understad why it was made "required" to be used on this project.

Isn't a good idea to add  a String equivalent of each function?

The way things are now i can't use it on legacy minecraft versions. (Like 1.7.10 in my case)

**Comment by iGabyTM** [comment]
Components is what newer versions of Minecraft use. Even though spigot still has string methods that's just because MD_5 wants to have "backwards compatibility", but internally things are converted to components.
Minecraft 1.7.10 is **VERY** old and I doubt that @ipsk will add direct support for it on any of the libs. You can try adventure, it _might_ work on 1.7.

**Comment by evernife** [comment]
Sure, no problem at all, it's understandable.

I will leave my fork here for anyone wanting these three things:

1- 1.7.10 Modded Suport ( as well as 1.12.2 modded suport) (both these versions are legacy, so they do not have adventure on it)
2- Removal of Adventure's Component usage
*3- Removal of Deprecated Code.*

![image](https://user-images.githubusercontent.com/11357801/141948255-eb5faeef-6e2c-4a8a-8358-3f5fd31f2ba7.png)


https://github.com/evernife/triumph-gui/releases/tag/3.0.4-e1

**Comment by ipsk** [comment]
Adventure is **not** required, it is the default and it is the recommended way but not required. You can still use `new Gui(rows, "title as string")` and `ItemBuilder.from(material).setName("item name as string")`, just make sure to exclude it from the Gradle/Maven dependency.

Adventure **does** support 1.7.10, however this does not have direct support to it, if it works or not I am unsure as I have never tested.

Modded support? Do you mean actually provide support for other platforms or do you mean support for mixes like Mohist?
If you mean different platforms, yes this will be implemented at some point, mainly Fabric and Sponge, but Forge could be planned.
However if you mean things like Mohist then no I do not plan to support that.

**Comment by evernife** [comment]
On forge i meanted Hybrid like Cauldron/Thermos/Crucible(1.7.10) and Mohist(1.7.10)

I totally understand, its a pain to give support to them, that is where I enter :D
My job is give support for things people wil usually not waste time with.

I may give a try on Adventure in the future, but as legacy builds are, there might be zero advantage using Adventure on them.
