### ISSUE TITLE
Allow directly update of updateItem() with GuiItem as arg

### ISSUE THREAD

**Issue by EverNife** [TriumphTeam/triumph-gui#43]
Shoulden't this allow directly update?

https://github.com/TriumphTeam/triumph-gui/blob/master/core/src/main/java/dev/triumphteam/gui/guis/BaseGui.java#L515

If we have a menu, for example, with a border that spins, we need to make two codes, one for setting the guiItems and another for updating it afterwards.

![SomeGif](https://user-images.githubusercontent.com/11357801/145491332-9817eec8-9a17-4f73-a94f-39abbac037c3.gif)

We would have to duplicate this code bellow, one for setting it and one after to update it.

```java
    private void drawBackground(){
        for (int backgroundSlot : backgroundSlots) {
            if (this.gui.getGuiItem(backgroundSlot) != BLACK_BACKGROUND){
                this.gui.updateItem(backgroundSlot, BLACK_BACKGROUND);
            }
        }
        
        int[] movingSlots = getNext4MovingSlots();
       
        this.gui.updateItem(movingSlots[0], BLUE_BACKGROUND);
        this.gui.updateItem(movingSlots[1], BLUE_BACKGROUND);
        this.gui.updateItem(movingSlots[2], YELLOW_BACKGROUND);
        this.gui.updateItem(movingSlots[3], GREEN_BACKGROUND);
    }
```

**Comment by ipsk** [comment]
That's a good point, I'll make the change.

**Comment by ipsk** [comment]
Done, it now should update directly.
