### ISSUE TITLE
Error when i click in inventory on item equls is in set inventory

### ISSUE THREAD

**Issue by Osnixeroo** [TriumphTeam/triumph-gui#50]
Error: https://paste.gg/p/anonymous/8670ca75bd4940ed83354d03421e95b4

My code: https://paste.gg/p/anonymous/51501da084784093aa64fe52e49339bc

**Comment by efekurbann** [comment]
What is your version? It should not be a problem in 3.0.5 (https://github.com/TriumphTeam/triumph-gui/commit/b8832bcf379480ba9d52c6ca27986ca7db01467a)

**Comment by Osnixeroo** [comment]
> What is your version? It should not be a problem in 3.0.5 ([b8832bc](https://github.com/TriumphTeam/triumph-gui/commit/b8832bcf379480ba9d52c6ca27986ca7db01467a))

Thanks a lot! I was have 3.0.0 version!
