### ISSUE TITLE
Error on gui open

### ISSUE THREAD

**Issue by Kr1S-D** [TriumphTeam/triumph-gui#57]
Hello can u kindly help me ? 
https://pastebin.com/0uzeYHbv

**Comment by ipsk** [comment]
Hey, if the plugin is Paper (1.16.5+) only, I would suggest you exclude adventure from the transitive dependencies. If the plugin accepts Spigot as well then I would suggest you relocate `net.kyori` into your own package.

**Comment by Kr1S-D** [comment]
fixed thx
