### ISSUE TITLE
Add a method to make the gui not closeable by client

### ISSUE THREAD

**Issue by ImFound** [TriumphTeam/triumph-gui#59]
It would be nice to make a method that does not allow the client to close the gui, until the plugin closes it.

**Comment by iGabyTM** [comment]
I don't think that's very do-able, afaik there's no way to check if the inventory was closed by a player or plugin.

**Comment by ImFound** [comment]
![immagine](https://user-images.githubusercontent.com/76497130/156886740-f0122294-8e3c-4693-b0f4-e28f1f3bb900.png)
are u sure?

**Comment by BlitzOffline** [comment]
Pretty sure that's a paper only thing.

**Comment by ImFound** [comment]
umhh now I check

**Comment by BlitzOffline** [comment]
I did check. It is. 
![image](https://user-images.githubusercontent.com/52609756/156886789-41e53819-75d3-46b5-b442-e7db75bb4ede.png)
![image](https://user-images.githubusercontent.com/52609756/156886793-d02836f9-cd76-4899-9fb8-065bcc9fe4fa.png)

First is spigot, second is paper.

**Comment by iGabyTM** [comment]
You can implement that on your end though
https://github.com/TriumphTeam/triumph-gui/blob/7b5817595acdfc150c2426267818503b48acb122/core/src/main/java/dev/triumphteam/gui/guis/BaseGui.java#L409-L417

**Comment by ImFound** [comment]
oh okay, thanks
