### ISSUE TITLE
Package-private methods

### ISSUE THREAD

**Issue by zrdzn** [TriumphTeam/triumph-gui#62]
Hello, I have a question about two methods located in the PaginatedGui. Does page number getter/setter really need to be package-private scope? I think it would be nice if (at least) getter was public since you can use it for e.g. placeholders (item lore maybe? Like, on what page are you currently on). If it is package-private for any reason - that's okay, but I guess it's not really done on purpose.

https://github.com/TriumphTeam/triumph-gui/blob/7b5817595acdfc150c2426267818503b48acb122/core/src/main/java/dev/triumphteam/gui/guis/PaginatedGui.java#L457-L473

**Comment by ipsk** [comment]
Hello!
Those methods, specially the getter are actually not supposed to exist, I just haven't had the time to clean it up. You can already get the page number with `getCurrentPageNum`, as for setting, I never thought it would be necessary but if needed I can make it public.

**Comment by zrdzn** [comment]
I don't know how I missed these methods when I needed to use them, but anyway, thanks for replying!
