### ISSUE TITLE
When fill material is AIR, whole GUI is bricked 

### ISSUE THREAD

**Issue by Szczurowsky** [TriumphTeam/triumph-gui#68]
When setting fill material to AIR, GUI being unusable, clicked items not reacting properly

**Comment by iGabyTM** [comment]
I don't think AIR is considered a valid item. If you don't want items in your GUI, look into slot actions. https://github.com/TriumphTeam/triumph-gui/blob/eb16b04329c746989fa1847a6cf4cd3333e6c369/core/src/main/java/dev/triumphteam/gui/guis/BaseGui.java#L429-L451
