### ISSUE TITLE
GuiType.HOPPER doesn't work

### ISSUE THREAD

**Issue by RoughlyUnderscore** [TriumphTeam/triumph-gui#69]
When creating a GUI with GuiType.HOPPER, the GuiItems in it won't have their actions activated (in asGuiItem)

**Comment by BlitzOffline** [comment]
So I've done some intensive testing and here's some information I got so far:

- This happens on SPIGOT but not on PAPER
- This seems to not be an issue with SPIGOT itself but rather with the library.

My test code:
- My own implementation: https://paste.helpch.at/ecihesutac.rb
- triumph-gui implementation: https://paste.helpch.at/obecukober.pl

When I get some extra time I will start looking into why this breaks if no one finds the reason before me.
