### ISSUE TITLE
add support kotlin

### ISSUE THREAD

**Issue by robalmeister** [TriumphTeam/triumph-gui#71]
add

**Comment by knightzmc** [comment]
kotlin is interoperable with java

PR or shut

**Comment by LichtHund** [comment]
What "Kotlin support" do you want? It works perfectly fine already.

**Comment by robalmeister** [comment]
the problem is that the rows in the basin do not work what should work

**Comment by robalmeister** [comment]
and there is a chest and in addition, if it gives 27 slots, I get 9 slots and the code is: `Gui.gui()
                    .title(ChatHelper.parse("<green>text")) //minimessage
                    .disableAllInteractions()
                    .rows(27)
                    .create()`

**Comment by BlitzOffline** [comment]
> and there is a chest and in addition, if it gives 27 slots, I get 9 slots and the code is: `Gui.gui().title(ChatHelper.parse("<green>text")).disableAllInteractions().rows(27).create()`

I'm sorry but what made you think that rows, sets the slots field? That does set the rows. the maximum amount of rows in a chest gui is 6.

**Comment by robalmeister** [comment]
thanks
