### ISSUE TITLE
Plugin works in 1.8 but not in 1.18

### ISSUE THREAD

**Issue by nay-cat** [TriumphTeam/triumph-gui#75]
On a server with ViaVersion, in **1.8** the plugin works correctly, but in **1.18** it does not work, idk if it's a bug or I'm doing something wrong

Specifically, in **1.8** when clicking the events work, it does not allow objects to be moved.

In **1.18** clicking does not work the events and lets steal objects

Thanks in advance

**Comment by LichtHund** [comment]
I'll need a bit more information than that. Some code if possible.

**Comment by xNayra** [comment]
literally the documentation code
```java
gui = Gui.gui()
                .title(Component.text(Objects.requireNonNull(getConfig().getString("Inventory.name"))))
                .rows(1)
                .create();
// yes i know setName is deprecated        
GuiItem basic = ItemBuilder.from(Material.BOOK).setName("name").asGuiItem(event -> {
                Player player = (Player) event.getWhoClicked();
});

gui.disableAllInteractions();
gui.setItem(2, basic);
```
                
In both versions the inventory opens, but in 1.18 events don't work and items can be stolen

**Comment by iGabyTM** [comment]
Can you try without any other plugins? I use the lib on 1.18 and works just fine

**Comment by LichtHund** [comment]
Also, one more thing, what version is the server? 1.8 or 1.18? Because it sounds like the issue is connecting from 1.18 on a 1.8 server? Is that correct?
Just asking so I can test it.

**Comment by xNayra** [comment]
> Also, one more thing, what version is the server? 1.8 or 1.18? Because it sounds like the issue is connecting from 1.18 on a 1.8 server? Is that correct?
> Just asking so I can test it.

The server is in 1.18, we use viaversion, the strange thing is that a user who joins in 1.8 works well with the inventory and a user who joins in 1.18 does not work well, the plugin is made with spigot 1.18

**Comment by iGabyTM** [comment]
You mean you use ViaBackwards AND Viaersion.

**Comment by LichtHund** [comment]
I'll test it.

**Comment by xNayra** [comment]
> I'll test it.

Thanks
