### ISSUE TITLE
java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component

### ISSUE THREAD

**Issue by zaDR0tic** [TriumphTeam/triumph-gui#76]
what is that problem?
i'am import that, but console send me this, when i try to open gui

version is 1.18.2

![image](https://user-images.githubusercontent.com/70453716/189418411-466e8196-93a9-4a77-88f1-b8948844fc77.png)

**Comment by FCKJohni** [comment]
Can you provide your pom.xml/build.gradle(.kts)

**Comment by zaDR0tic** [comment]
> 

```
plugins {
    id 'java'
    id "com.github.johnrengelman.shadow" version "7.1.1"
}

shadowJar {
    relocate("dev.triumphteam.gui", "zaksen.cave.guis.gui")
}

group = 'zaksen.cave'
version = '0.1'

repositories {
    mavenCentral()
    maven {
        name = 'spigotmc-repo'
        url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'
    }
    maven {
        name = 'sonatype'
        url = 'https://oss.sonatype.org/content/groups/public/'
    }
}

dependencies {
    compileOnly 'org.spigotmc:spigot-api:1.18.2-R0.1-SNAPSHOT'
    implementation "dev.triumphteam:triumph-gui:3.1.2"
}

def targetJavaVersion = 17
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release = targetJavaVersion
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
```

**Comment by FCKJohni** [comment]
Since you are using spigot you have 2 options. Either manually include kyori or use paper rather then spigot

**Comment by zaDR0tic** [comment]
> Since you are using spigot you have 2 options. Either manually include kyori or use paper rather then spigot
how i can include kyori?
i doesn't want use paper, because i need bungeecord

**Comment by iGabyTM** [comment]
Can you provide us the full error?
@FCKJohni adventure is provided by the triumph-gui

**Comment by FCKJohni** [comment]
https://docs.adventure.kyori.net/getting-started.html

**Comment by FCKJohni** [comment]
> Can you provide us the full error?
> @FCKJohni adventure is provided by triumph-gui

Isn't it just compileOnly?

**Comment by zaDR0tic** [comment]
> Can you provide us the full error? @FCKJohni adventure is provided by triumph-gui
![image](https://user-images.githubusercontent.com/70453716/189419666-57381a66-0f88-4597-a541-adc0dd8791b8.png)

server doesn't crush, but console send this

**Comment by iGabyTM** [comment]
> > Can you provide us the full error?
> > @FCKJohni adventure is provided by triumph-gui
> 
> Isn't it just compileOnly? 

No

**Comment by LichtHund** [comment]
The issue here is how you're building the project, you need to build with the `shadowJar` task.
I also suggest you relocate adventure as well, use `net.kyori` to `zaksen.cave.kyori` or something like that.

And as for the paper comment, you can use Bungeecord with Paper as well.

**Comment by zaDR0tic** [comment]
> The issue here is how you're building the project, you need to build with the `shadowJar` task. I also suggest you relocate adventure as well, use `net.kyori` to `zaksen.cave.kyori` or something like that.
> 
> And as for the paper comment, you can use Bungeecord with Paper as well.

oh yes? hmm

**Comment by zaDR0tic** [comment]
> 

something like this?
![image](https://user-images.githubusercontent.com/70453716/189420354-09679904-0be3-45c6-af3f-e71f2fc60f4f.png)

**Comment by zaDR0tic** [comment]
oh, that work! thanks!
