### ISSUE TITLE
Support for `libraries`

### ISSUE THREAD

**Issue by Vrganj** [TriumphTeam/triumph-gui#82]
I can use the library by shading, but not the newer `libraries` feature in plugin.yml.

The issue is this:
https://github.com/TriumphTeam/triumph-gui/blob/master/core/src/main/java/dev/triumphteam/gui/guis/BaseGui.java#L67

JavaPlugin#getProvidingPlugin throws an exception since libraries aren't provided by plugins.

**Comment by Vrganj** [comment]
Same issue occurs in `core/src/main/java/dev/triumphteam/gui/components/nbt/Pdc.java`

**Comment by iGabyTM** [comment]
The library depends on a plugin to register events and work with PDC, I don't think anything can be done to support spigot's libraries system.

**Comment by Vrganj** [comment]
I think the plugin that's using the library should be able to supply the instance.
Of course this can be a fallback method if you don't supply it.

**Comment by LichtHund** [comment]
In version 3.1.11 I have added a method `TriumphGui.init(plugin)` where you can manually init the plugin that the library uses, which should fix this issue.
