### ISSUE TITLE
Is there a way to make GUI Items non draggable?

### ISSUE THREAD

**Issue by Osanchez** [TriumphTeam/triumph-gui#84]
does the lib include something that prevents items in gui from being dragged around? or do i need to implement a custom listener on my end

**Comment by LichtHund** [comment]
You can use `Gui#setDragAction` and cancel it to prevent it from happening.

**Comment by Osanchez** [comment]
ah okay, by any chance would this modifier do the same
disableItemSwap().

**Comment by LichtHund** [comment]
No, swap is different, for example when you click `2` on your keyboard while hovering an item, it'll swap the item you're hovering with the item at position `2` on the hotbar.
