### ISSUE TITLE
Cannot use setItem with normal GUI

### ISSUE THREAD

**Issue by 0PandaDEV** [TriumphTeam/triumph-gui#92]
Hey, I'm testing out the GUIs and noticed that the normal GUI does not have the function setItem
![image](https://user-images.githubusercontent.com/70103896/236160957-8df36ac2-7f8f-4693-af2d-a56ae51fdd6f.png)

**Comment by 0PandaDEV** [comment]
I just noticed when change the hey variable to public static and access it through another method, it works.
![image](https://user-images.githubusercontent.com/70103896/236162874-0c786f02-8f02-47e6-911a-84fcecc02020.png)

**Comment by 0PandaDEV** [comment]
But that is not very comfortable

**Comment by iGabyTM** [comment]
That might be an issue with the IDE, methods don't just come and go xD

**Comment by 0PandaDEV** [comment]
So should I just restart IntelliJ?

**Comment by iGabyTM** [comment]
Oh.. I've just realized what you are doing, the reason the method is not working is because you can not call methods outside other methods. You are trying to use `setItem()` inside the `Test` class itself and not inside a method within that class.

**Comment by 0PandaDEV** [comment]
thanks fixed :)
