### ISSUE TITLE
Different NBT Attributes of Default Cooldowns, Refills, and Similar Items Compared to TriumphGUI

### ISSUE THREAD

**Issue by zuffew** [TriumphTeam/triumph-gui#93]
This guide explains the variances in NBT attributes between default cooldowns, refills, and similar items in Minecraft compared to those presented through TriumphGUI.

TriumphGUI is a plugin designed to create user interfaces (GUIs) in Minecraft, offering convenient customization options for items, including the manipulation of NBT attributes. However, it's important to note that default cooldowns, refills, and similar items may have different NBT attributes compared to those showcased in TriumphGUI.

By default, Minecraft implements specific NBT attributes for various game mechanics, such as item cooldowns and refill functionalities. These default attributes are distinct from those modified through TriumphGUI or other similar plugins. While TriumphGUI allows for extensive customization of NBT tags and item behaviors, it operates within the framework defined by the game's default attributes.

To fully understand and modify the NBT attributes of default cooldowns, refills, or other related functionalities, it's recommended to consult the official Minecraft documentation or relevant community resources. These sources will provide detailed information on default NBT attributes and any available methods for customization or modification.

Please note that this information is based on the general understanding of Minecraft gameplay mechanics and may vary depending on the specific version, configuration, or modifications applied to your Minecraft server.

**Comment by LichtHund** [comment]
Okay?
