### ISSUE TITLE
NBT Items on gui

### ISSUE THREAD

**Issue by zuffew** [TriumphTeam/triumph-gui#94]
Golden apples and other such items have different nbt than the default ones from the game

**Comment by iGabyTM** [comment]
Yes, that's normal behavior because a custom NBT tag is set by the library to separate the items from normal items.

**Comment by zuffew** [comment]
And there is a chance to restore the old nbt, because I need it and I already have everything ready under your GUI

**Comment by LichtHund** [comment]
Wdym? Can you give me an example of how the NBT are wrong?

**Comment by LichtHund** [comment]
Items built for the GUI shouldn't be given to players, they are there to have click events, the NBT is necessary for that. If you want to give players items use the #build function in the ItemBuilder instead of turning it into a GuiItem.

**Comment by zuffew** [comment]
do you have example code?

**Comment by LichtHund** [comment]
`ItemBuilder.from(material).name(text("Hi")).asGuiItem();` meant for GUis, adds NBT to identify item and use click actions.
`ItemBuilder.from(material).name(text("Hi")).build();` gives you an ItemStack that you can use as you would any other item, stacks the way you want.

**Comment by zuffew** [comment]
I did it and it doesn't work, do you have any discord contact?

**Comment by LichtHund** [comment]
Yes, the discord is on the read-me page. https://mattstudios.me/discord
