### ISSUE TITLE
Java 17 compatibility?

### ISSUE THREAD

**Issue by mkko120** [TriumphTeam/triumph-gui#98]
Hello
I use your project a lot, but one thing that haunts me down is that there is no java 17 compatibility. I want to use FAWE API which requires it so if migration to 17 could be possible it would be very much appreciated!

**Comment by iGabyTM** [comment]
What makes you say it doesnt work with java 17?

**Comment by mkko120** [comment]
After i try to compile my project, it throws unsupported class version error.

**Comment by iGabyTM** [comment]
It works fine. Make sure the error is coming from the lib.

**Comment by mkko120** [comment]
Okay, I will look into it and update you if i find something.

**Comment by mkko120** [comment]
okay nevermind, i was just using too old shade plugin, sorry for the false alert!
